baseURL = "https://alb-dev.github.io/sixspeck.github.io/"
languageCode = "en-us"
title = "Sixspeck"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
[[Params.listeLangues]]
code = "en"

# meta data
author = "Themefisher"
description = "This is meta description"

# Gestion des langues : FR / EN / NL / DE
[Languages]
############# 1 - Site en ENGLISH
[Languages.en]
weight = 1
languageCode = "en-us"
title = "Sixspeck"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Sixspeck were heroes are born"
description = "Vom Büro gepeinigten ITler zum Athleten."
#button  = true
#btnText = "Know More"
#btnURL  = "https://themefisher.com/"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL   = "https://www.youtube.com/embed/btPJPFnesV4"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Wir haben uns öffentliche Gyms für eine lange Zeit angeschaut"
description = "Der Erfolg in öffentlichen Gyms mag durchausgegeben sein, jedoch konnte ein intensives Training nur im Sixspeck durchgeführt werden wo wir auf unsere eingene Kompetenzn zurück greifen konnten."

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "No pain no gain"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Workout together get stronger together"
subtitle= "Nur im Team ist mit man stark und das gleich gilt auch für einen soliden workout"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "workout"
url     = "workout"
weight  = 4
[[menu.nav]]
name    = "protein"
url     = "protein"
weight  = 5
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 6

# Footer Service Menu
[[menu.service]]
name    = "Workout"
url     = "service"
weight  = 1
[[menu.service]]
name    = "training"
url     = "service"
weight  = 2

# Footer Quick links Menu
[[menu.quicklink]]
name    = "partners"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "faqs"
url     = "about"
weight  = 2
